const CONSTANTS = {
    TRY_TO_FETCH: "TRY_TO_FETCH",
    FETCH_SUCCESS: "FETCH_SUCCESS",
    FETCH_ERROR: "FETCH_ERROR",

    SORT_ID_ASCENDING: "SORT_ID_ASCENDING",
    SORT_ID_DESCENDING: "SORT_ID_DESCENDING",

    SORT_FN_ASCENDING: "SORT_FN_ASCENDING",
    SORT_FN_DESCENDING: "SORT_FN_DESCENDING",

    SORT_LN_ASCENDING: "SORT_LN_ASCENDING",
    SORT_LN_DESCENDING: "SORT_LN_DESCENDING",

    SORT_EMAIL_ASCENDING: "SORT_EMAIL_ASCENDING",
    SORT_EMAIL_DESCENDING: "SORT_EMAIL_DESCENDING",

    SORT_PHONE_ASCENDING: "SORT_PHONE_ASCENDING",
    SORT_PHONE_DESCENDING: "SORT_PHONE_DESCENDING",

    SORT_STATE_ASCENDING: "SORT_STATE_ASCENDING",
    SORT_STATE_DESCENDING: "SORT_STATE_DESCENDING",

    SEARCH_CHANGE: "SEARCH_CHANGE",
    PAGE_CHANGE: "PAGE_CHANGE",
    MAX_PAGES: "MAX_PAGES",
    STATE_FILTER: "STATE_FILTER",
    CHANGE_CHOSEN_PERSON: "CHANGE_CHOSEN_PERSON",
};

export default CONSTANTS
